# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=120)),
                ('post_pub_date', models.DateTimeField(verbose_name=b'publish date')),
                ('post_msg', models.TextField()),
                ('post_sign', models.CharField(max_length=24)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
